HW4_objects_and_clases
LidaShatkovska/python-course-alphabet pull request #4
Opened 2019-05-03 12:34 UTC by LidaShatkovska

Якщо вам викине ексепшн "Count cars more then count place. RUN PROGRAM AGAIN" перераньте ще раз код доки не отримаєте результат.

2019-05-03 12:43 UTC, LidaShatkovska commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW4_objects_and_clases](https://trello.com/c/XXH3k6L2/66-hw4objectsandclases)

2019-05-06 09:32 UTC, ekut2104 commented on objects_and_classes/homework/homework.py
type - builtin name краще використати інше імя типу car_type  або щось інше

2019-05-06 09:38 UTC, LidaShatkovska commented on objects_and_classes/homework/homework.py
Ок. Ти знаєш я теж думала про це, що якось дивно type передавати, але я слідувала умові задачі. Виправлю. Ти підтвердив мої здогадки :)

2019-05-06 09:44 UTC, ekut2104 commented on objects_and_classes/homework/homework.py
поки не розумію сенсу використання двох методів що виконують одну задачу... а саме __str__ i __repr__. поясніть будьласка)

2019-05-06 09:50 UTC, ekut2104 commented on objects_and_classes/homework/homework.py
price - значення типу float.
думаю булоб непогано дописати тип очікуваних данних

2019-05-06 09:52 UTC, LidaShatkovska commented on objects_and_classes/homework/homework.py
При виводі(logs, print) автомобілю повинні зазначатися всі його атрибути.
По умові задачі і лекції я зрозуміла, що в __str__ задаємо формат виводу строки, а  __repr__ спрацьовує, коли нема опису __str__ або для виводу logs, тому я щоб не переписувати в __repr__ повторно __str__, просто його там викликала. Але якщо нема різонв такого робити, то я видалю без проблем, бо вони по суті одне і те ж роблять

2019-05-06 10:13 UTC, ekut2104 commented on objects_and_classes/homework/homework.py
> +                  )
CAR1:  
Car produser: BMW, type: Sedan, number: a8c2ae20-ef0c-4451-b300-facdc1b63f45, price: 940.4544598303223, spend mileage: 99433.89090191058
CAR2:  
Car produser: BMW, type: Wagon, number: 44a7da9a-b764-4464-80fa-e1fd4f1ac4d8, price: 256.4213108710543, spend mileage: 438103.942249093
на мою думку точність в продажу машин до 9 знаків після коми надмірна))) як в ціні так і в пробігу

2019-05-06 10:31 UTC, LidaShatkovska commented on objects_and_classes/homework/homework.py
> +                  )
👍 Псіханула так псіханула :)

2019-05-06 11:30 UTC, ekut2104 commented on objects_and_classes/homework/homework.py
> +
наскільки я розумію список машин в гаражі ти придумуєш вручну?
було бцікаво реалізувати генерування списку (любої довжини )машин  при створенні гаражу, щоб коли ми створюємо гараж він вже був заповнений. якщо є бажпння)

2019-05-06 12:41 UTC, LidaShatkovska commented on objects_and_classes/homework/homework.py
> +                  )
Поправила всі коменти

2019-05-06 15:19 UTC, ekut2104 commented on objects_and_classes/homework/homework.py
>          all_cars = "".join(str(item) for item in self.cars)
all_cars -  вона потрібна для чогось? - не бачу де вона використовується

2019-05-06 15:28 UTC, ekut2104 commented on objects_and_classes/homework/homework.py
> +    def compare_cesar(cesar_list):
в класі зазвичай перший аргумент методу - self. інакше треба використати @classmetod or @staticmethod

2019-05-06 16:21 UTC, ekut2104 commented on objects_and_classes/homework/homework.py
>      def сars_count(self):
PyCharm мені вказує що в назві є і кирилиця і латинка ... зверни увагу.

2019-05-06 16:26 UTC, ekut2104 requested changes

2019-05-06 16:26 UTC, ekut2104 commented on objects_and_classes/homework/homework.py
new_car_max_free_garage = 0 - не бачу де ця змінна використовується. чи потрібна вона

2019-05-06 16:26 UTC, ekut2104 commented on objects_and_classes/homework/homework.py
if garage == None: - зазвичай краще писати is None

2019-05-06 19:10 UTC, LidaShatkovska commented on objects_and_classes/homework/homework.py
>          all_cars = "".join(str(item) for item in self.cars)
+ Вже нема :)

2019-05-06 19:12 UTC, LidaShatkovska commented on objects_and_classes/homework/homework.py
> +    def compare_cesar(cesar_list):
+ Добавила @staticmethod, думаю там не доцільно буде передавати self, я і розраховувала як статичний метод, але видно не докінця ще з оголошенням статичних методів розібралась. Ще почитаю. Дякую

2019-05-06 19:13 UTC, LidaShatkovska commented on objects_and_classes/homework/homework.py
>      def сars_count(self):
Виправила, дійсно і в мене кидало попередження, але я не звернула увагу. Тепер буду звертати увагу на зелене підкреслення :)

2019-05-06 19:13 UTC, LidaShatkovska commented on objects_and_classes/homework/homework.py
+ Виправила, дякую.

2019-05-07 09:18 UTC, ekut2104 approved these changes

2019-05-07 09:39 UTC, merged