HW5_serialization
LidaShatkovska/python-course-alphabet pull request #5
Opened 2019-05-09 14:35 UTC by LidaShatkovska

2019-05-09 14:36 UTC, LidaShatkovska commented
![](https://github.trello.services/images/mini-trello-icon.png) [SHW5-serialization](https://trello.com/c/Zr2KvsVQ/79-shw5-serialization)

2019-05-11 17:36 UTC, LidaShatkovska commented
У мене така трохи дивна ідея була, спробувати зробити кожен клас різним форматом, це так щоб познайомитись з мини ближче :) Якщо це погана ідея, то якось не дуже хочеться перероблювати :(

2019-05-23 19:44 UTC, yuriimchg requested changes

2019-05-23 19:44 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
>  from constants import CARS_TYPES
константи краще імпортувати одним рядком через кому

2019-05-23 19:44 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +        car_data = {"price": obj.price, "car_type": obj.car_type, "number": str(obj.number), \
```suggestion
        car_data = {"price": obj.price,
                           "car_type": obj.car_type,
                            "number": str(obj.number), 
                            "producer": obj.producer,
                             "mileage": obj.mileage
                             }
```

2019-05-23 19:44 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +        self.garage_set = ({'town': self.town, 'places': self.places, 'owner': self.owner, \
тут можна так само форматувати, як в 108-109 рядках

2019-05-23 19:44 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +        car_data = {"price": obj.price, "car_type": obj.car_type, "number": str(obj.number), \
так трохи більш читабельно

2019-05-23 19:44 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +            return ("Garage haven't got any free places")
тут не потрібні дужки

2019-05-23 19:44 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +        with open("pickle_data.txt", "wb") as file:
pickle - це байти, тому їх не варто зберігати в текстові файли. Для цього варто використовувати бінарні типи такі як `pickle` чи `dat`

2019-05-23 19:44 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +    def from_yaml(cls, new_garage_dict):
для чого тут @classmethod, якщо ти потім явно вказуєш, клас, чий об'єкт, повертається в цьому методі?

2019-05-23 19:44 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +    def instance_from_yaml_file(cls):
те саме запитання про @classmethod

2019-05-23 19:44 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +    # print ("CAR2: ", car2)
старайся не залишати закоментований код, якщо все ок працює й без нього. Він тільки захаращує файлики і псує читабельність

2019-05-23 19:44 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +            self.cagarage_cars.remove(my_car)
`garage_cars` ?

2019-05-23 19:44 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +    garage1 = Garage.instance_from_yaml_file()
в мене тут впав скрипт, оскільки не було `yaml` файлика з гаражем. Для всіх інших файликів все ок

2019-05-23 19:44 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +    def __init__(self, price: float, car_type: str,
це краще одним рядком, навіть, якщо довжина більша за 79

2019-05-23 19:44 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> -               f"number: {self.number}, price: {self.price}, mileage: {self.mileage}"
чому б не уникнути дублювання коду і не повернути тут self.car_set?

2019-05-23 19:44 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
>      @classmethod
тут немає потреби використовувати `@classmethod`
краще `@staticmethod`

2019-05-23 19:44 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> -            print(f"NEW_CAR_TYPE: {type(new_car)}\nNEW_CAR_FROM_JSON_FILE: {new_car}")
а чим відрізняється цей метод від методу `from_json` (123 рядок)?

2019-05-23 19:44 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> -    def __init__(self, town: str, places: int, garage_cars: List[Car], owner=None):
тут так само краще одним рядком

2019-05-23 19:44 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
>          self.garage_cars = garage_cars if garage_cars is not None else []
` self.garage_cars = garage_cars if garage_cars else []`

2019-05-23 19:44 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
>          self.garage_cars = garage_cars if garage_cars is not None else []
або ` self.garage_cars = garage_cars or []`

2019-05-23 19:44 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
>      def __repr__(self):
а для чого тут символ нового рядка?

2019-05-23 19:44 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +        pickle_formatted_str = codecs\
це краще одним рядком

2019-06-04 11:11 UTC, LidaShatkovska commented on objects_and_classes/homework/homework.py
> -            print(f"NEW_CAR_TYPE: {type(new_car)}\nNEW_CAR_FROM_JSON_FILE: {new_car}")
Не зовсім зрозуміла питання. В from_json я створюю інстанс класу, а в instance_from_json_file вичитую дані в форматі json з файлу і створюю інстанс викликаючи метод from_json

2019-06-04 11:12 UTC, LidaShatkovska commented on objects_and_classes/homework/homework.py
>      def __repr__(self):
Або я раніше вже поміняла і забула, бо зараз тут нема символу нового рядка

2019-06-07 09:33 UTC, yuriimchg approved these changes

2019-06-09 19:47 UTC, merged