Hw6 oop
LidaShatkovska/python-course-alphabet pull request #6
Opened 2019-05-20 13:41 UTC by LidaShatkovska

2019-05-20 13:42 UTC, LidaShatkovska commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW6-oop](https://trello.com/c/ZoZNT5U6/96-hw6-oop)

2019-05-21 15:49 UTC, ekut2104 commented on oop/homework.py
> +    def _check_saturation_level(self, value):
_check_saturation_level  - в цей метод як я розумію ти передаєш вже не значення value а значення self.saturation_level - тож параметр valueтрохи вводить в оману))

2019-05-21 15:50 UTC, ekut2104 commented on oop/homework.py
> +        if value < 0:
те саме і тут...ти порівнюєш в першому if значення value а далі вже  if self.saturation_level > 100:

2019-05-21 15:54 UTC, ekut2104 commented on oop/homework.py
> +        if value < 0:
if value < 0:                                           - тут парметр value
            self.saturation_level = 0
        if self.saturation_level > 100:      -  тут вже ні...
            self.saturation_level = 100
        return self.saturation_level

2019-05-21 16:03 UTC, ekut2104 commented on oop/homework.py
> +        print("Your cat ran {} kilometers".format(ran_km))
за умовою завдання просять       return     text like this: f"Your cat ran {ran_km} kilometers"

2019-05-21 16:07 UTC, ekut2104 commented on oop/homework.py
> +        if product == 'gazelle':
працює, та можна в компактно в один рядочок записати )

2019-05-21 16:08 UTC, ekut2104 commented on oop/homework.py
> +            return self.saturation_level
`        if self.saturation_level == 0:
            return "Your cat is died :("
        else:
            return `self.saturation_level`

працює, та можна  компактно в один рядочок записати)

2019-05-21 16:21 UTC, ekut2104 commented on oop/homework.py
> +            self._increase_saturation_level(15)
метод eat в Cat повертає значення...перевизначений метод eat в Cheetah не повертає нічого. чому відрізняються ці методи?)

2019-05-21 16:30 UTC, ekut2104 commented on oop/homework.py
>      def __init__(self, age):
непоганоб було додати очікуваний тип вхідних параметрів

2019-05-21 16:35 UTC, ekut2104 commented on oop/homework.py
> +        return math.floor(self.width / roll_width_m) / math.floor(roll_length_m / self.height)
гарне вирішення. але щоб не імпортувати цілу бібліотеку можна скористатись отриманням цілої частини від ділення. -  досить просто

2019-05-21 16:43 UTC, ekut2104 commented on oop/homework.py
> +    @staticmethod
за умовою завдання просять не створювати нових методів !!!! DON'T WRITE NEW METHODS TO THIS CLASS EXCEPT FOR THOSE LISTED BELOW !!!

2019-05-21 16:51 UTC, ekut2104 commented on oop/homework.py
> +        pass
це можна прибрати

2019-05-21 16:59 UTC, ekut2104 requested changes
гарна робота. є незначні зауваження. дивись коменти

2019-05-22 18:11 UTC, LidaShatkovska commented on oop/homework.py
> +    def _check_saturation_level(self, value):
так ти правильно розумієш :) добре я назву по іншому

2019-05-22 18:16 UTC, LidaShatkovska commented on oop/homework.py
> +    @staticmethod
Ну так  порушила правило, лише з тою ціллю щоб не дублувати однаковий код в кожному методі.

2019-05-23 07:56 UTC, LidaShatkovska commented on oop/homework.py
> +    def _check_saturation_level(self, value):
+

2019-05-23 07:56 UTC, LidaShatkovska commented on oop/homework.py
> +        if value < 0:
+

2019-05-23 07:57 UTC, LidaShatkovska commented on oop/homework.py
> +        print("Your cat ran {} kilometers".format(ran_km))
+

2019-05-23 07:57 UTC, LidaShatkovska commented on oop/homework.py
> +            return self.saturation_level
+

2019-05-23 07:57 UTC, LidaShatkovska commented on oop/homework.py
> +            self._increase_saturation_level(15)
Тільки моєю неуважністю :) Виправила

2019-05-23 07:57 UTC, LidaShatkovska commented on oop/homework.py
>      def __init__(self, age):
Скрізь зобавила

2019-05-23 07:58 UTC, LidaShatkovska commented on oop/homework.py
> +        return math.floor(self.width / roll_width_m) / math.floor(roll_length_m / self.height)
Зробила

2019-05-23 07:58 UTC, LidaShatkovska commented on oop/homework.py
> +        pass
Упс, профтик +

2019-05-23 13:54 UTC, ekut2104 commented on oop/homework.py
> +import math
якщо не використовуєш то видали)

2019-05-23 13:58 UTC, ekut2104 commented on oop/homework.py
відповідно до PEP8 між методами в класі один рядок пустий має бути

2019-05-23 14:00 UTC, ekut2104 commented on oop/homework.py
> +        return (self.width // roll_width_m ) / (roll_length_m // self.height)
метод очікує int а результат ділення float

2019-05-23 14:04 UTC, ekut2104 commented on oop/homework.py
> +    def create_wall(self, width: int, height: int) -> Wall:
перевір чи повертає цей метод щось і чи варто зось очікувати

2019-05-23 14:05 UTC, ekut2104 commented on oop/homework.py
> +    def create_roof(self, width: int, height: int, roof_type: str) -> Roof:
перевір чи повертає цей метод щось і чи варто зось очікувати

2019-05-23 14:05 UTC, ekut2104 commented on oop/homework.py
> +    def create_window(self, width: int, height: int) -> Window:
перевір чи повертає цей метод щось і чи варто щось очікувати

2019-05-23 14:05 UTC, ekut2104 commented on oop/homework.py
> +    def create_door(self, width: int, height: int) -> Door:
перевір чи повертає цей метод щось і чи варто щось очікувати

2019-05-23 14:06 UTC, ekut2104 requested changes
ще є нюанси))

2019-05-24 09:23 UTC, LidaShatkovska commented on oop/homework.py
> +        return (self.width // roll_width_m ) / (roll_length_m // self.height)
тоді буду повертати float, бо якщо робити int(self.width // roll_width_m ) / (roll_length_m // self.height) то падає тест 20 == 22. Нормально так буде?

2019-05-24 09:24 UTC, LidaShatkovska commented on oop/homework.py
> +    def create_window(self, width: int, height: int) -> Window:
Не повертає, ти правий, аналогічно в попередніх.

2019-05-24 11:05 UTC, ekut2104 approved these changes

2019-05-24 12:38 UTC, merged