HW9
LidaShatkovska/python-course-alphabet pull request #7
Opened 2019-06-05 16:10 UTC by LidaShatkovska

2019-06-05 16:12 UTC, LidaShatkovska commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW9_FLASK](https://trello.com/c/7eNW2IzU/117-hw9flask)

2019-06-09 15:28 UTC, yuriimchg requested changes
привіт
перевірив дз

не дуже зручно користуватись постменом для цього, але то таке)
сподіваюся, в наступному буде хоч трохи розмітки :wink: 

також є штука, яку варто пофіксити, бо в оригінальному варіанті аппка не запуститься (app, рядок 41)

2019-06-09 15:28 UTC, yuriimchg commented on flask-lesson_1/Flask_project/app.py
> +if __name__ == 'main':
```suggestion
if __name__ == '__main__':
```

2019-06-09 19:53 UTC, LidaShatkovska commented on flask-lesson_1/Flask_project/app.py
> +if __name__ == 'main':
Дякую! Поправила. В наступній домашці постараюсь пооригінальніше зробити з розміткою :)

2019-06-10 14:59 UTC, yuriimchg approved these changes

2019-06-10 15:02 UTC, merged